language: python
branches:
  only:
    - master
python:
  - "2.7"
sudo: false
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - py.test -v tests 
  - cd docs; make html linkcheck
